Import creation functions
stactools-packages/nrcan-landcover pull request #3
Opened 2021-07-09 20:25 UTC by jbants

This PR allows a python interpreter to see the commands used to create the STAC objects.

ex.
```python
>>> from stactools import nrcan_landcover
>>> nrcan_landcover.
nrcan_landcover.constants           nrcan_landcover.create_item(        nrcan_landcover.stac                
nrcan_landcover.create_collection(  nrcan_landcover.register_plugin(    nrcan_landcover.stactools
```

2021-07-12 04:05 UTC, cuttlefish requested changes
I'm not sure what the intent is here, but it will fail the linter since `create_item` and `create_collection` don't get used in the file.

2021-07-13 08:08 UTC, jbants commented
When I was using `nrcan_landcover` in a python interpreter, I tried tab autocomplete to see what functions were available. I think autocomplete was added in python 3.6? 

Adding the imports to `__init__.py` solved the tab autocomplete issue for me.

2021-07-13 08:40 UTC, jbants commented
No sure why Devin's stuff is included. Either way, adding `# noqa ` works.
https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html#in-line-ignoring-errors

2021-07-13 09:46 UTC, cuttlefish commented
I rebased to fix the mangled merge. You'll have to wipe out your local branch before you pull.

I now see what you're trying to do. That should work, but we should probably define `__all__` as well.

2021-07-13 16:01 UTC, bluegeo approved these changes
This appears to be passing the linter, so I don't see any harm

2021-07-15 17:39 UTC, bluegeo commented
Closing because fixed in 578749cb0cc71b1d3cd4ca6306e019c0e386b4cb

2021-07-15 17:39 UTC, closed without merging